### ISSUE TITLE
Use micoarch-level package to enable optimized builds for x86-64 instruction sets

### ISSUE THREAD

**Issue by carterbox** [conda-forge/rav1e-feedstock#8]
Just leaving some links/notes here that are relevant to enabling arch-aware builds of this package.

# Notes

https://github.com/xiph/rav1e?tab=readme-ov-file#target-specific-builds
https://github.com/conda-forge/microarch-level-feedstock
https://github.com/conda-forge/conda-forge.github.io/issues/1261

```
(rust) bash-5.2$ rustc --print target-cpus
Available CPUs for this target:
    x86-64                  - This is the default target CPU for the current build target (currently x86_64-unknown-linux-gnu).
    x86-64-v2
    x86-64-v3
    x86-64-v4
```

# TODOS

- [x] Do some tests to determine if there are significant gains from arch-aware optimizations
- [ ] Figure out the state of instruction set detection for this channel
  - https://github.com/conda-forge/microarch-level-feedstock/pull/2
- [ ] Enable instruction set build variants via build_config.

**Comment by carterbox** [comment]
I ran the benchmarking tests with and without x86 optimzations

```
# Enable microarchitecture optimizations
export RUSTFLAGS="${RUSTFLAGS} -C target-cpu=x86-64"

[ build and install ... ]

cargo test

cargo install cargo-criterion

cargo criterion --features=bench
```

But on my personal computer (zen2 - Ryzen 5 3600 - x86 v3), I don't see any difference in the  benchmark times? All the tests I ran are very short though, so maybe I'm not running long enough tests or my BIOS settings are not set correctly.

**Comment by hmaarrfk** [comment]
in 2025 i likely have machines that I can test this on.

if you make the PR after https://github.com/conda-forge/rav1e-feedstock/pull/11 I can probably build out and test a few
